#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 1 07:03:58 2022

@author: groupelegant
"""

#Import libraries
# from matplotlib.backend_bases import LocationEvent
import streamlit as st
import pandas as pd
import numpy as np


from PIL import Image



#load the model from disk
import joblib
filename = 'RandomForestRegressor.sav'
model = joblib.load(filename)

#Import python scripts
from preprocessing import preprocess

def main():
    #Setting Application title
    st.title('Fenyx Autoscout24 Model App')

      #Setting Application description
    st.markdown("""
     :dart: Data for Autoscout24 \n
     :dart:  Data for Autoscout24. \n
    """)
    st.markdown("<h3></h3>", unsafe_allow_html=True)

    #Setting Application sidebar default
    colours_name = ['Please choose your colour','Grey', 'White', 'Black', 'Red', 'Silver', 'Brown', 'Blue',
       'Violet', 'Beige', 'Yellow', 'Green', 'Orange', 'Bronze', 'Gold']
    drivetrain_name = ['Front', '4WD', 'Rear']
    location_names = ['LOON OP ZAND',
 'HEERLEN',
 'BREDA',
 'BAARLE-NASSAU',
 'ZUTPHEN',
 'ALMERE',
 'HAAKSBERGEN',
 'HAAKSBERGEN',
 'WEZEP',
 'UTRECHT',
 'HEESCH',
 'VALKENBURG AAN DE GEUL',
 'NIJKERK GLD',
 'GRONINGEN',
 'DEN BOSCH',
 'AMSTERDAM',
 'ROTTERDAM',
 'GOES',
 'SOEST',
 'MEPPEL',
 'DOETINCHEM',
 'RENSWOUDE',
 'Oldenzaal',
 'EDE GLD',
 'HAARLEM',
 'FIJNAART',
 'Ridderkerk',
 'FIJNAART',
 'UITHOORN',
 'DELDEN',
 'Culemborg',
 'SOEST',
 'BLEISWIJK',
 'ZEVENBERGEN',
 'KRUININGEN',
 'DRONTEN',
 'VOORSCHOTEN',
 'Alphen aan den Rijn',
 'BEVERWIJK',
 'ROTTERDAM',
 'PURMEREND',
 'ALMELO',
 'DOETINCHEM',
 'Werkendam',
 'HARDERWIJK',
 'RIDDERKERK',
 'BEEK EN DONK',
 'OSS',
 'ROTTERDAM',
 'APELDOORN',
 'ZUID BEIJERLAND',
 'GORINCHEM',
 'FRANEKER',
 'HAZERSWOUDE-DORP',
 'OSS',
 'ZWOLLE',
 'SCHAGEN',
 'HAARLEM',
 'HAARLEM',
 'VELSERBROEK',
 'CUIJK',
 'TILBURG',
 'VINKEVEEN',
 'AMSTERDAM',
 'OOSTERHOUT NB',
 'EINDHOVEN',
 'BARNEVELD',
 'Schiedam',
 'nijmegen',
 'SCHAGEN',
 'OOSTERHOUT',
 'TILBURG',
 'ZWANENBURG',
 'KWINTSHEUL',
 'MIJDRECHT',
 'HEERENVEEN',
 'Amsterdam',
 'Apeldoorn',
 'ALMERE',
 'HAARSTEEG',
 'Huizen',
 'METEREN',
 'APELDOORN',
 'ST MICHIELSGESTEL',
 'LOENEN AAN DE VECHT',
 'HILLEGOM',
 'DINTELOORD',
 'ULICOTEN',
 'BATHMEN',
 'OSS',
 'GOES',
 'RIJSSEN',
 'AMSTERDAM',
 'WEKEROM',
 'HEIKANT',
 'LEENDE',
 'KROMMENIE',
 'WOUDRICHEM',
 'AMERSFOORT',
 'Enter',
 'EDE GLD',
 'Apeldoorn',
 'LEIDERDORP',
 'BERKEL EN RODENRIJS',
 'EMMEN',
 'ROTTERDAM',
 'SOEST',
 'Eindhoven',
 'HENGELO',
 'RIDDERKERK',
 'ETTEN-LEUR',
 'WIERDEN',
 'MAKKUM FR',
 'VAASSEN',
 'UITGEEST',
 'GARDEREN',
 'SCHIJNDEL',
 'TER AAR',
 'ALPHEN AAN DEN RIJN',
 'APELDOORN',
 'HOLTEN',
 'BOXTEL',
 'WILP',
 'BOXTEL',
 'GOES',
 'Apeldoorn',
 'Enschede',
 'VLAARDINGEN',
 'Heinenoord',
 'MIJDRECHT',
 'ETTEN-LEUR',
 'LEIDERDORP',
 'WAALWIJK',
 'NIJKERK',
 'ERMELO',
 'HEERHUGOWAARD',
 'CULEMBORG',
 'EMMEN',
 'DRACHTEN',
 'LEEUWARDEN',
 'DORDRECHT',
 'SON',
 'ROOSENDAAL',
 'RUINEN',
 'APELDOORN',
 'PURMEREND',
 'VELSERBROEK',
 'HAARLEM',
 'HAARLEM',
 'HAARLEM',
 'DOETINCHEM',
 'NIJKERKERVEEN',
 's-Hertogenbosch',
 's-Hertogenbosch',
 's-Hertogenbosch',
 'BARNEVELD',
 'Den Haag',
 'Bergschenhoek',
 'ROTTERDAM',
 'Purmerend',
 'GELDERMALSEN',
 'WIERINGERWERF',
 'LEEK',
 'Amsterdam',
 'Den Haag',
 'HEERHUGOWAARD',
 'GAMEREN',
 'NIJKERK',
 'ZUIDBROEK',
 'OUD BEIJERLAND',
 'VINKEVEEN',
 'VENDDRIEL',
 'TILBURG',
 'ELST',
 'ALPHEN AAN DE RIJN',
 'NIJKERKERVEEN',
 'APELDOORN',
 'MARRUM',
 'Gemert',
 'TILBURG',
 'WINTERSWIJK',
 'AMSTENRADE',
 'VAASSEN',
 'Valkenswaard',
 'TILBURG',
 'OCHTEN',
 'OBDAM',
 'NIEUWLEUSEN',
 'AALSMEER',
 'BREUKELEN',
 'Schijndel',
 'HOLLANDSCHEVELD',
 'RHENEN',
 'HOLLANDSCHEVELD',
 'ARNHEM',
 'TILBURG',
 'HEERHUGOWAARD',
 'MEERSSEN',
 'HOLLANDSCHEVELD',
 'Schijndel',
 'HALSTEREN',
 'Schijndel',
 'Krimpen aan de IJssel',
 'LUNTEREN',
 'ZWOLLE',
 'Son en Breugel',
 'HEEZE',
 'HOLLANDSCHEVELD',
 'GIETEN',
 'NIJVERDAL',
 'Krimpen aan de IJssel',
 'HOLLANDSCHEVELD',
 'Montfoort',
 'ZWOLLE',
 'Krimpen aan de IJssel',
 'BREUKELEN',
 'HARDERWIJK',
 'HOLLANDSCHEVELD',
 'WOERDEN',
 'MANDER',
 'HOOGEVEEN',
 'OSS',
 'RHENEN',
 'BREUKELEN',
 'VOERENDAAL',
 'NIEUWLEUSEN',
 'MEERKERK',
 'HELMOND',
 'LEMMER',
 'Montfoort',
 'GEESTEREN',
 'WAGENINGEN',
 'TILBURG',
 'Bennekom',
 'VAASSEN',
 'HEERENVEEN',
 'SINT- OEDENRODE',
 'UDEN',
 'HENGELO',
 'EMMEN',
 'SPIJKENISSE',
 'ANGEREN',
 'VENLO',
 'VEGHEL',
 'KROMMENIE',
 'ROTTERDAM',
 'APELDOORN',
 'HALSTEREN',
 'VENLO',
 'VALKENSWAARD',
 'OCHTEN',
 'OCHTEN',
 'EINDHOVEN',
 'HALSTEREN',
 'VORSTENBOSCH',
 'Valkenswaard',
 'BERLICUM',
 'DE RIPS',
 'SURHUISTERVEEN',
 'DOETINCHEM',
 'LUNTEREN',
 'GRONINGEN',
 'Schijndel',
 'VOORSCHOTEN',
 'SCHOONHOVEN',
 'BREUKELEN',
 'LUNTEREN',
 'Lutten',
 'MOORDRECHT',
 'APELDOORN',
 'SPRANG-CAPELLE',
 'EMMELOORD',
 "'S-GRAVENHAGE",
 'Arnhem',
 'ARNHEM',
 'GOIRLE',
 'Arnhem',
 'SURHUISTERVEEN',
 'APELDOORN',
 'APELDOORN',
 'MIERLO',
 'TILBURG',
 'HOOFDDORP',
 'HEERENVEEN',
 'TWELLO',
 'NAARDEN',
 'HEERENVEEN',
 'VEENENDAAL',
 'HARDERWIJK',
 'ALMERE',
 'HARDERWIJK',
 'VOORSCHOTEN',
 'TILBURG',
 'Zoetermeer',
 'GENEMUIDEN',
 'VOORSCHOTEN',
 'HEERENVEEN',
 'HOOFDDORP',
 'TILBURG',
 'ZEEWOLDE',
 'STOLWIJK',
 'ZWOLLE',
 'DEN HAAG',
 "'S-GRAVENHAGE",
 'HEERHUGOWAARD',
 'VARSSEVELD',
 'ALMELO',
 'JOURE',
 'STOLWIJK',
 'VINKEVEEN',
 'MIJDRECHT',
 'TILBURG',
 'ROTTERDAM',
 'OSS',
 'BOSKOOP',
 'DEN BOSCH',
 'WEKEROM',
 'NAARDEN',
 'ZUID BEIJERLAND',
 'BILTHOVEN',
 'LEMELERVELD',
 'TER AAR',
 'Utrecht',
 'Amsterdam',
 'SCHAGEN',
 'HARDINXVELD-GIESSENDAM',
 'SOESTERBERG',
 'MALDEN',
 'HEERENVEEN',
 'ENKHUIZEN',
 'SPIJKENISSE',
 'APELDOORN',
 'Roosendaal',
 'GEESBRUG',
 'VARSSEVELD',
 'KOOTSTERTILLE',
 'ULFT',
 'SCHIEDAM',
 'SCHIEDAM',
 'ROOSENDAAL',
 'LUNTEREN',
 'TILBURG',
 'VLAARDINGEN',
 'AMSTERDAM',
 'LIEREN (BEEKBERGEN)',
 'hollandscheveld',
 'Almere',
 'Bussum',
 'ROOSENDAAL',
 'HEESWIJK-DINTHER',
 'TILBURG',
 'HOLLANDSCHEVELD',
 'NIJMEGEN',
 'MOORDRECHT',
 'DRIEL',
 'VEENENDAAL',
 'ZWOLLE',
 'BARNEVELD',
 'ZUILICHEM',
 'WADDINXVEEN',
 'HOLLANDSCHEVELD',
 'ZUILICHEM',
 'ZUILICHEM',
 'HOOFDDORP',
 'AMSTERDAM',
 'HEERLEN',
 'BREUKELEN',
 'ZUILICHEM',
 'VENLO',
 'RIJSSEN',
 'EMMELOORD',
 'WESTERVOORT',
 'MOORDRECHT',
 'WEZEP',
 'BEEK EN DONK',
 'WEZEP',
 'VEENENDAAL',
 'BUDEL',
 'UDEN',
 'GIETEN',
 'BREUKELEN',
 'MEERSSEN',
 'HAAKSBERGEN',
 'GROOTEBROEK',
 'DOETINCHEM',
 'GEESTEREN',
 'NIJMEGEN',
 'LAREN GLD',
 'HOLLANDSCHEVELD',
 'WIJCHEN',
 'ZWARTEWAAL',
 'ROGGEL',
 'OSS',
 'TILBURG',
 'Valkenswaard',
 'ROTTERDAM',
 'KLAZIENAVEEN',
 "'S-HEERENBERG",
 'ROTTERDAM',
 'LEKKERKERK',
 'HAAKSBERGEN',
 'DORDRECHT',
 'DRONTEN',
 'WIERDEN',
 'KLAZIENAVEEN',
 'BEILEN',
 'HAAKSBERGEN',
 'HEERHUGOWAARD',
 'HEESCH',
 'KLAZIENAVEEN',
 'WIERDEN',
 'LOON OP ZAND',
 'RIJSWIJK ZH',
 'DRONTEN',
 'BEEK EN DONK',
 'ROTTERDAM',
 'Krimpen aan de IJssel',
 'BRUCHT',
 'HENGELO',
 'Son en Breugel',
 'DRONTEN',
 'TILBURG',
 'HENGELO',
 'BAARLE-NASSAU',
 'HOLLANDSCHEVELD',
 'VALKENSWAARD',
 'Haarlem',
 'MIDWOUD',
 'Krimpen aan de IJssel',
 'OSS',
 'ZUILICHEM',
 'ZUILICHEM',
 'ZUILICHEM',
 'WIJCHEN',
 'SURHUISTERVEEN',
 'DRONTEN',
 'HOLLANDSCHEVELD',
 'ABCOUDE',
 'ENSCHEDE',
 'UTRECHT',
 'BEVERWIJK',
 'WORMERVEER',
 'BILTHOVEN',
 'Den haag',
 'BATHMEN',
 'SUSTEREN',
 'WEKEROM',
 'STAPHORST',
 'Dreumel',
 'WEZEP',
 'SOEST',
 'NUENEN',
 'HAARLEM',
 'HARDERWIJK',
 'VLISSINGEN',
 'BOXTEL',
 'AMSTELVEEN',
 'GAANDEREN',
 'HEERDE',
 'TILBURG',
 'HAARLEM',
 'MEERSSEN',
 'HAARLEM',
 'HAARLEM',
 'WIJK EN AALBURG',
 'GELEEN',
 'Wieringerwerf',
 'HENGELO',
 'SOEST',
 'HOLTEN',
 'KERKRADE',
 'HOOGEZAND',
 'OUDDORP ZH',
 'LIEMPDE',
 'ALPHEN AAN DEN RIJN',
 'hoogvliet',
 'KLAZINAVEEN',
 'MANDERVEEN',
 'HEERHUGOWAARD',
 'HOOGEZAND',
 'ZEIST',
 'S-HERTOGENBOSCH',
 'BOXTEL',
 'GOES',
 'STEENWIJK',
 'VENLO',
 'GELEEN',
 'BEUNINGEN',
 'Beek en Donk',
 'suwald',
 'APELDOORN',
 'Hapert',
 'NIJKERK',
 'WEERT',
 'LELYSTAD',
 'PUTTEN',
 'EMMELOORD',
 'MANDERVEEN',
 'MAASTRICHT',
 'DRACHTEN',
 'HOOGEZAND',
 'BERLICUM',
 'CULEMBORG',
 'HOOGEZAND',
 'BUDEL',
 'AALSMEER',
 'EMMEN',
 'SOMEREN',
 'OUD-BEIJERLAND',
 'Beilen',
 'UTRECHT',
 "'S-HERTOGENBOSCH",
 'Losser',
 'Eindhoven',
 'NIJKERK',
 'Heerhugowaard',
 'Uitgeest',
 'EMMEN',
 'Varsselder',
 'Papenhoven',
 'Amsterdam',
 'DRACHTEN',
 'Lemmer',
 'WINTERSWIJK',
 'SITTARD',
 'ETTEN-LEUR',
 'GENNEP',
 'HOOGEZAND',
 '‘t ZAND',
 'ST MICHIELSGESTEL',
 'ZALTBOMMEL',
 'CREIL',
 'DORDRECHT',
 'ZEEWOLDE',
 'Uithoorn',
 'ZEVENAAR',
 'ZUIDWOLDE',
 'HAARLEM',
 'GOES',
 'ROOSENDAAL',
 'rotterdam',
 'BEEKBERGEN',
 'Etten-Leur',
 'KERKRADE',
 'Amsterdam',
 'ZEVENHUIZEN',
 'Ridderkerk',
 'NUNSPEET',
 'GOES',
 'ZOETERMEER',
 'MALDEN',
 'Wijchen',
 'VEENENDAAL',
 'PAPENDRECHT',
 'KOOTSTERTILLE',
 'DONGEN',
 'FIJNAART',
 'APELDOORN',
 'ARNHEM',
 'RENSWOUDE',
 'APELDOORN',
 'ALMELO',
 'SURHUISTERVEEN',
 'TER AAR',
 'FINSTERWOLDE',
 'GELEEN',
 'ZAANDAM',
 'MADE',
 'EDE',
 'HAAKSBERGEN',
 'GOUDSWAARD',
 'OPMEER',
 'DRUNEN',
 'TYNAARLO',
 'BOSKOOP',
 'ZWIJNDRECHT',
 'ROOSENDAAL',
 'PAPENDRECHT',
 'GOES',
 'Molenlanden',
 'TILBURG',
 'HENGELO OV',
 'KATWIJK',
 'VENLO',
 'LEEK',
 'ULFT',
 'TER AAR',
 'VLAARDINGEN',
 'SCHOONHOVEN',
 'Drimmelen',
 'RAAMSDONKSVEER',
 'HOOGEVEEN',
 'LOENEN GLD',
 'MARRUM',
 "'S-GRAVENHAGE",
 'WOERDEN',
 'GOES',
 'VENDDRIEL',
 'MIDDELHARNIS',
 'OOSTERHOUT',
 'KRABBENDIJKE',
 'DRUNEN',
 'LOSSER',
 'DRUNEN',
 'ZUILICHEM',
 'SURHUISTERVEEN',
 'Benningbroek',
 'GORINCHEM',
 'HEERLEN',
 'GELDROP',
 'DE GOORN',
 'Zandvoort',
 'HEERHUGOWAARD',
 'ROOSENDAAL',
 'HARMELEN',
 'TEUGE',
 'RIDDERKERK',
 'DRIEBERGEN',
 'ROTTERDAM',
 'DORDRECHT',
 'VLIJMEN',
 'ALBLASSERDAM',
 'TEGELEN',
 'TILBURG',
 'MANDERVEEN',
 'OOSTDIJK',
 'WIERDEN',
 'RUINERWOLD',
 'ASSEN',
 'RIJSSEN',
 'DUIVEN',
 'Maasdriel',
 'Nieuw-Vennep',
 'Putten',
 'Dongen',
 'Wommels',
 'SOESTERBERG',
 'ALMERE',
 'Wommels',
 'Goes',
 'ZEVENBERGEN',
 'NUENEN',
 'VENDDRIEL',
 'Vroomshoop',
 'CULEMBORG',
 'HOOGEZAND',
 'Deurningen',
 'EMMEN',
 'Joure',
 'Breda',
 'POELDIJK',
 'Wijchen',
 'TILBURG',
 'HEERLEN',
 'VENLO',
 'ANGEREN',
 'HARDERWIJK',
 'ZEVENHUIZEN',
 'VELP',
 'Weert',
 'AALTEN',
 'DEN HAAG',
 'ULESTRATEN',
 'OUD GASTEL',
 'AMSTERDAM',
 'VEENENDAAL',
 'AMERSFOORT',
 'Voorthuizen',
 'HOOGEVEEN',
 'BENNEKOM',
 'ROTTERDAM',
 'ROTTERDAM',
 'HEERLEN',
 'ASSEN',
 'NIJMEGEN',
 'ASSEN',
 'HAAKSBERGEN',
 'OUD GASTEL',
 "'s-Gravenhage",
 'DELFT',
 'SCHAIJK',
 'WORMERVEER',
 'ERMELO',
 'VENLO',
 'LOENEN AAN DE VECHT',
 'NIJKERK',
 'RIJKEVOORT',
 'KOEKANGE',
 'ERMELO',
 'VLISSINGEN',
 'ALMERE',
 'NEER',
 'MIJDRECHT',
 'RIJNSBURG',
 'GRONINGEN',
 '`S-GRAVENHAGE',
 'SOMEREN',
 'MAASBRACHT',
 'SITTARD',
 'PUTTEN',
 'ETTEN GLD',
 'HOOFDDORP',
 'DOETINCHEM',
 'OSS',
 'TILBURG',
 'HOOFDDORP',
 'EDE GLD',
 'OUD GASTEL',
 'LOENEN AAN DE VECHT',
 'EMMEN',
 'GOOR',
 'EINDHOVEN',
 'ENTER',
 'HEESCH',
 'RENSWOUDE',
 'VOORSCHOTEN',
 'Eindhoven',
 'ZWIJNDRECHT',
 'VOORSCHOTEN',
 'TILBURG',
 '`S-GRAVENHAGE',
 'MAURIK',
 'BERGSCHENHOEK',
 'RHENEN',
 'DEN HAAG',
 'ROSMALEN',
 'DE RIPS',
 'ROTTERDAM',
 'OLDENZAAL',
 'GASSEL',
 'EMMEN',
 'ZWOLLE',
 '`S-GRAVENHAGE',
 'SCHERPENZEEL',
 'UITHOORN',
 'Krimpen aan de IJssel',
 'HEERLEN',
 'EINDHOVEN',
 '`S-GRAVENHAGE',
 'RHENEN',
 'RODEN',
 'ALKMAAR',
 'BREDA',
 'ALKMAAR',
 'ECHT',
 'DEVENTER',
 'NISTELRODE',
 'WERKENDAM',
 'HEERLEN',
 'ALMERE',
 'ECHT',
 'CAPELLE A/D IJSSEL',
 'WORMERVEER',
 'HEERHUGOWAARD',
 'UITHOORN',
 'AALTEN',
 'DRACHTEN',
 'EPE',
 'MEPPEL',
 'EDERVEEN',
 'MAARHEEZE',
 'Cruquius',
 'TILBURG',
 'SOEST',
 'AALTEN',
 'LIMMEN',
 'LOENEN AAN DE VECHT',
 'ALKMAAR',
 'SITTARD',
 'Tolbert',
 'HEEMSKERK',
 'RIDDERKERK',
 'Valkenswaard',
 'DORDRECHT',
 'GORREDIJK',
 'GELDERMALSEN',
 'EINDHOVEN',
 'NIJMEGEN',
 'OUD GASTEL',
 'UTRECHT',
 'WEERT',
 'OIRSCHOT',
 'TILBURG',
 'HEIJEN',
 '`S-GRAVENHAGE',
 'APELDOORN',
 'ERMELO',
 'TILBURG',
 'HEERLEN',
 'RHENEN',
 'MAASTRICHT',
 'DIRKSLAND',
 'HOOFDDORP',
 'LELYSTAD',
 'AALTEN',
 'LIENDEN',
 'AALTEN',
 'ASSEN',
 'LEIDEN',
 'LEIDERDORP',
 'TILBURG',
 'KRIMPEN AAN DEN IJSSEL',
 'VEENENDAAL',
 'ZEVENBERGEN',
 'OUD BEIJERLAND',
 'HAARLEM',
 'ARNHEM',
 'BENNEKOM',
 'LIENDEN',
 'LOENEN AAN DE VECHT',
 'DINTELOORD',
 'NIJKERKERVEEN',
 'LOSSER',
 'RUINERWOLD',
 'RHENEN',
 'MAASTRICHT',
 'Lochem',
 'Blaricum',
 'ELSHOUT',
 "'T HARDE",
 'VELSEN-NOORD',
 'ALMERE',
 'BLEISWIJK',
 'RHENEN',
 'De Koog',
 'HEERLEN',
 'ULFT',
 'DOETINCHEM',
 'GELEEN',
 'MIJDRECHT',
 'NAARDEN',
 'ALPHEN AAN DEN RIJN',
 'TILBURG',
 'ROERDALEN',
 'Kerkrade',
 'KLIMMEN',
 'MEPPEL',
 'HOOFDDORP',
 'GOUDRIAAN',
 'HOOFDDORP',
 'SURHUISTERVEEN',
 'PURMEREND',
 'EEFDE',
 'RIJSSEN',
 'Valkenswaard',
 'Cruquius',
 'ERMELO',
 'TILBURG',
 'ARNHEM',
 'NIEUWER TER AA (BREUKELEN)',
 'HILVARENBEEK',
 'DEVENTER',
 'ERMELO',
 'BOXTEL',
 'Amersfoort',
 'MEPPEL',
 'Hapert',
 'BOXTEL',
 'GELDERMALSEN',
 'HEEZE',
 'AMSTENRADE',
 'HUIZEN',
 'GOES',
 'HEERENVEEN',
 'EINDHOVEN',
 'HARDERWIJK',
 'Roden',
 'VOORHOUT',
 'NIEUW-WEERDINGE',
 'LEERDAM',
 'WIJCHEN',
 'Rijswijk',
 'NIEUWER TER AA (BREUKELEN)',
 'BEVERWIJK',
 'LELYSTAD',
 'Oldenzaal',
 'OISTERWIJK',
 'BREDA',
 'MEPPEL',
 'ALPHEN AAN DEN RIJN',
 'TIEL',
 'KAATSHEUVEL',
 'RIDDERKERK',
 'MARUM',
 'WOERDEN',
 'APELDOORN',
 "'S-GRAVENHAGE",
 'TILBURG',
 'Almelo',
 'OOSTERHOUT',
 'TWELLO',
 'OSS',
 'KATWIJK',
 'BAARN',
 'ETTEN-LEUR',
 'HAAKSBERGEN',
 'DEN HAAG',
 'Blaricum',
 'Hengelo',
 'NIJKERKERVEEN',
 'ZEVENAAR',
 'ALPHEN AAN DEN RIJN',
 'GENDEREN',
 'Roosendaal',
 'MAREN-KESSEL',
 'NAARDEN',
 'DIEREN',
 'ALMERE',
 'LEIDERDORP',
 'ZEVENBERGEN',
 'HENGELO OV',
 "'S-GRAVENHAGE",
 'SOESTERBERG',
 'SOESTERBERG',
 'ALPHEN AAN DEN RIJN',
 'BROEKLAND',
 'ERMELO',
 'HONSELERSDIJK',
 'LEIDERDORP',
 'BEVERWIJK',
 'DORDRECHT',
 'RUINERWOLD',
 'TEUGE',
 'ARNHEM',
 'VUGHT',
 'WESTERBORK',
 'ZUIDLAND',
 'TEUGE',
 'APELDOORN',
 'EINDHOVEN',
 'ALBLASSERDAM',
 'VLAARDINGEN',
 'VEEN',
 'APELDOORN',
 'VALKENBURG ZH',
 'HEERENVEEN',
 'BERLICUM',
 'Krimpen aan de IJssel',
 'LEERDAM',
 'VEENENDAAL',
 'UDEN',
 'WIJCHEN',
 'BREDA',
 'URK',
 'MEPPEL',
 'GIETEN',
 'WINTERSWIJK',
 'HOLLANDSCHEVELD',
 'LEENDE',
 'WINTERSWIJK',
 'ZWOLLE',
 'WAGENINGEN',
 'HELMOND',
 'Klundert',
 'ZWOLLE',
 'DRIEL',
 'SCHAGEN',
 'APELDOORN',
 'HOLLANDSCHEVELD',
 'LEENDE',
 'HELLENDOORN',
 'ROTTERDAM',
 'HARDERWIJK',
 'HENGELO',
 'AMMERZODEN',
 'GEMERT',
 'TWELLO',
 'BLITTERSWIJCK',
 'SON EN BREUGEL',
 'Den Bosch Rosmalen',
 'ERMELO',
 'MIDDELHARNIS',
 'ERMELO',
 'GOES',
 'BLEISWIJK',
 'Reusel',
 'UTRECHT',
 'Overloon',
 'Valkenswaard',
 'AMSTERDAM',
 'ELSHOUT',
 'PUTTEN',
 'HEERLEN',
 'DRUTEN',
 'GOIRLE',
 'Best',
 'HILVERSUM',
 'UTRECHT',
 'Weert',
 'KRAGGENBURG',
 'WIJCHEN',
 'AALTEN',
 'BOXTEL',
 'KOEKANGE',
 'GRONINGEN',
 'IJSSELMUIDEN',
 'GOES',
 'STOLWIJK',
 'LEERDAM',
 'HAARSTEEG']
    image = Image.open('App.png')
    image1 = Image.open('importance.png')
    add_selectbox = st.sidebar.selectbox(
    "How would you like to predict?", ("Online", "Batch"))
    st.sidebar.info('This app is created to predict Autoscout24 use case')
    st.sidebar.image(image)
    st.sidebar.info('This app uses Random Forest Model')
    st.sidebar.image(image1)
    if add_selectbox == "Online":
        st.info("Input data below")
        st.subheader("Initials of Vehicle data")
        #Based on our optimal features selection
        location = st.selectbox('Location', location_names)
        First_Registration_Year = st.slider('First Registration Year' ,0,2022,1980)
        Power_kW = st.slider('Power kW', 0,220,0)
        Empty_Weight_kg = st.slider('Empty Weight (kg)', 0,5000,300)
        mileage = st.slider('Mileage of Vehicle (km) ', 0,300000,1000)
        gears = st.slider('Gears', 0,9,0)
        make_model = st.slider('Make Model',0,800,0)
        cylinders = st.slider('Cylinders', 0,12,0)
        Engine_Size_cc = st.slider('Engine Size (cc)', 0,3000,600)
        Gearbox = st.slider('Gearbox', 0,2,0)
        fuel_type = st.slider('Fuel Type', 0,9,0)
        fuel_country = st.slider('Fuel Country', 0,7,0)
        fuel_city = st.slider('Fuel City', 0,16,0)
        fuel_comb = st.slider('Fuel Comb', 0,10,0)
        co2_emissions = st.slider('CO2 Emissions', 0,300,0)
        body_type = st.slider('Body Type', 0,5,0)
        seats = st.slider('Count of Seats', 0,9,0)
        doors = st.slider('Count of Doors', 0,6,0)
        colour = st.selectbox('Colour', colours_name)
        upholstery = st.slider('Upholstery', 0,5,0)
        drivetrain = st.selectbox('Drivetrain', drivetrain_name)

     
        

        st.subheader("Details of Vehicle Data")                       
        title_0 = st.selectbox('LED Headlights:', ('No','Yes'))
        title_1 = st.selectbox('Digital cockpit:', ('No','Yes'))
        title_2 = st.selectbox('Heated streering weel:', ('No','Yes'))
        title_3 = st.selectbox('Panorama roof:', ('No','Yes'))
        title_4 = st.selectbox('Electrically adjustable seats:', ('No','Yes'))
        title_5 = st.selectbox('Emergency System:', ('No','Yes')) 
        title_6 = st.selectbox('Electric tailgate:', ('No','Yes'))
        title_7 = st.selectbox('High bean assist:', ('No','Yes'))  
        title_8 = st.selectbox('Full Service History:', ('No','Yes'))



        
        data = {
                'Location' : location,
                'First Registration Year':First_Registration_Year,
                'Power kW' : Power_kW,
                'Empty Weight (kg)': Empty_Weight_kg,
                'Mileage of Vehicle (km)': mileage,
                'Gears': gears,
                'Make Model': make_model,
                'Cylinders': cylinders,
                'Engine Size (cc)': Engine_Size_cc,
                'Gearbox': Gearbox,
                'Fuel Type': fuel_type,
                'Fuel Country' : fuel_country,
                'Fuel City' : fuel_city,
                'Fuel Comb' : fuel_comb,
                'CO2 Emissions': co2_emissions,
                'Body Type' : body_type,
                'Count of Seats': seats,
                'Count of Doors': doors,
                'Colour': colour,
                'Upholstery': upholstery,
                'Drivetrain' : drivetrain,
                
                'title_0':title_0, 
                'title_1':title_1, 
                'title_2':title_2, 
                'title_3':title_3, 
                'title_4':title_4,
                'title_5':title_5,
                'title_6':title_6, 
                'title_7':title_7, 
                'title_8':title_8, 
                                
                }

        features_df = pd.DataFrame.from_dict([data])
        st.markdown("<h3></h3>", unsafe_allow_html=True)
        st.write('Overview of input is shown below')
        st.markdown("<h3></h3>", unsafe_allow_html=True)
        st.dataframe(features_df)


        #Preprocess inputs
        preprocess_df = preprocess(features_df, 'Online')

        prediction = model.predict(preprocess_df)

        if st.button('Predict'):
            if prediction == 1:
                st.warning('Your vehicles value is:')

        

    else:
        st.subheader("Dataset upload")
        uploaded_file = st.file_uploader("Choose a file")
        if uploaded_file is not None:
            data = pd.read_csv(uploaded_file,encoding= 'utf-8')
            #Get overview of data
            st.write(data.head())
            st.markdown("<h3></h3>", unsafe_allow_html=True)
            #Preprocess inputs
            preprocess_df = preprocess(data, "Batch")
            if st.button('Predict'):
               #Get batch prediction
                prediction = model.predict(preprocess_df)
                prediction_df = pd.DataFrame(prediction, columns=["Predictions"])
                prediction_df = prediction_df.replace({1:'Yes, the passenger survive.', 0:'No, the passenger died'})

                st.markdown("<h3></h3>", unsafe_allow_html=True)
                st.subheader('Prediction')
                st.write(prediction_df)
            
if __name__ == '__main__':
        main()
